### ISSUE TITLE
Please provide a Dockerfile and a smoke test

### ISSUE THREAD

**Issue by 1605200517** [fmtvp/tal#227]
Thanks!

**Comment by watsond88** [comment]
Should this issue be on this repo?

**Comment by watsond88** [comment]
Issue from unknown user and not pertinent to this repo. Suspect meant for another repo.

**Comment by 1605200517** [comment]
hi,

I have contacted you in terms of the project mediafi.org. There is catalogue of components, and all SE vendors are kindly invited to provide Docker versions of their components. 
I cannot reach the contact given there for TAL: http://mediafi.org/?portfolio=tv-application-layer

Please help!!!

**Comment by tsadlerBBC** [comment]
Spoke to our product owner about this, and we do intend to progress this.

If it is trivial, we may do it imminently, otherwise, we're not sure when we will get round to this.

**Comment by tsadlerBBC** [comment]
This is not trivial, but we do intend to tackle this as part of our engagement with the mediafi project (prior to any TAL events).

**Comment by tsadlerBBC** [comment]
We expect this to be a contribution, rather than something we will be actioning ourselves.

**Comment by 1605200517** [comment]
FYI is this same or other tal?

https://github.com/ULANCFIC/tal/blob/master/Dockerfile

**Comment by tsadlerBBC** [comment]
ULANCFIC/tal is a fork of https://github.com/fmtvp/talexample, which is our example app rather than just the framework.
