### ISSUE TITLE
Live TV signal playback in SmartHub

### ISSUE THREAD

**Issue by xtazz** [fmtvp/tal#229]
Hi! 

I have an issue with broadcast TV playback on Samsung SmartHub 2014. Playback starts after I call webapis.tv.channel.tune() method, but the picture is displayed under the layout, but we want to display  it in specific block. Did you have such issues and maybe you know any solutions for this problem?

I've found an article about almost the same issue in your docs here:
http://fmtvp.github.io/tal/overview/new-media-playback.html

Do you know any way to play the video above all html layout?

Thanks in advance!

**Comment by sdclibbery** [comment]
Hi,

webapis.tv.channel.tune() is a Samsung specific API, which TAL abstracts
using the TAL broadcast API (see
http://fmtvp.github.io/tal/other/broadcast.html). The TAL broadcast API
includes the 'setPosition' function, which can be used to set the position
and size of the broadcast.

BTW, the New Media doc you linked is only relevant when playing IP video
using TAL, not for broadcast video.

Thanks,
Steve

**Comment by xtazz** [comment]
Thanks for fast reply! I know about setPosition function and I use it in my app, but anyway the video is still under all html :( Do you have any example app which uses TAL and samsung broadcast API? Thanks

**Comment by sdclibbery** [comment]
Hi,

TAL does not currently support placing broadcast video on top of HTML content; we're not sure if any devices are actually able to do that. 

We have the tal example app: https://github.com/fmtvp/talexample. But I don't think it uses the broadcast API, sorry :-/

Thanks,
Steve

**Comment by xtazz** [comment]
Ok, got it! I've already modified my layout for samsung to make player zone transparent, so now I can see broadcast video. Thanks anyway for the awesome library!
