### ISSUE TITLE
Readme.md has a link to a page not found

### ISSUE THREAD

**Issue by subsidel** [fmtvp/tal#255]
The last line of the readme is a broken link

`[![githalytics.com alpha](https://cruel-carlota.pagodabox.com/81b276db21d339cd95a3198c0aac146f "githalytics.com")](http://githalytics.com/fmtvp/TAL)`

**Comment by dhurrell** [comment]
Hello @davidbuckhurst! Do you know what happened to Githalytics? They seem to have dropped off the face of the earth.

Shall we just remove the tracking?

**Comment by davidbuckhurst** [comment]
Yeah, not needed anymore as we can get our traffic information from github's own analytics these days:

https://github.com/fmtvp/tal/graphs/traffic

**Comment by dhurrell** [comment]
Cool. Thanks. Now I'm wondering why we get a link in Opera's bug database... :)
