### ISSUE TITLE
ECMAScript 5 Support

### ISSUE THREAD

**Issue by joeyjojo** [fmtvp/tal#267]
I think its worth considering shimming out support for ECMAScript 5 (using es5-shim and sham) rather than doing things weirdly ourselves.

For instance Array.indexOf, this is ES5, so we have to provide a solution for using it.

Currently we have an implementation in browserdevice.js, as an outsider, this is a bit weird. Most JS developers would expect this to be on the Array prototype.

What this means is that we have also introduced duplication because intervalformat.js also has an implementation.

Further to that, the implementation we have doesn't match the spec as given (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf) and so is a bit different.

**Comment by tsadlerBBC** [comment]
Following discussions, this is not something we would want to introduce in TAL. es5-shim and sham can be used by TAL applications without it being a part of TAL, and we do not intend to replace the uses of browserDevice.arrayIndexOf within TAL.
