### ISSUE TITLE
Upgrade Travis CI job to use latest infrastructure

### ISSUE THREAD

**Issue by johnbeech** [fmtvp/tal#272]
When I visited:
* https://travis-ci.org/fmtvp/tal

I saw this message:
`This job ran on our legacy infrastructure. Please read our docs on how to upgrade`

Should we upgrade?
Travis CI have a page on that... http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade#Why-migrate-to-container-based-infrastructure%3F

**Comment by tsadlerBBC** [comment]
Done under pull request #280.
