### ISSUE TITLE
Configs for 2014 and 2015 Devices

### ISSUE THREAD

**Issue by johnbeech** [fmtvp/tal#277]
Where is your support for 2014 and 2015 devices?

The configs are 6 months out of date, at least:
* https://github.com/fmtvp/tal/tree/master/config/devices

Also, do you maintain a list of supported devices? The only reference I could find was on the FAQ pages:
* http://fmtvp.github.io/tal/faq.html

**Comment by solntcev** [comment]
Is there specifically LG WebOS and Samsung Tizen configs? That platforms differs from Mapple and Netcast supported in TAL.

**Comment by tsadlerBBC** [comment]
Hi Ivan,

We do not currently support Tizen, but #289 has updated the LG configs including some WebOS devices such as the lg tv_2014_highend. There is no special config required for WebOS as far as I can tell.

Thanks,

Tom

**Comment by solntcev** [comment]
Can you share your method of device detection? How to distinguish between midrange, highend and ultrahighend devices?

**Comment by tsadler1988** [comment]
Hi @solntcev, 

Sorry for the delay in response. 

Unfortunately we are unable to share our current method of device detection. We are hoping to replace our current device detection and make the new solution open source. @subsidel has done some work in this area in his personal space (https://gitlab.com/subsidel/priestly-identify) **but please note that this is not officially supported**.

Alternatively, if there is a particular device you want to know about, we can tell you what criteria our existing device detection uses to recognise said device.

Thanks,

Tom

**Comment by solntcev** [comment]
@tsadler1988, thanks.
Right now in master branch there are several LG configs:

    lg-tv_2015_a5lr-default.json
    lg-tv_2015_highend-default.json
    lg-tv_2015_lm14a-default.json
    lg-tv_2015_lm14alite-default.json
    lg-tv_2015_midrange-default.json
    lg-tv_2015_ultrahighend-default.json

How is appropriate config selected? Is it user-agent check? Do you have some hardcoded model list, which classifies model numbers as highend/midrange/etc?

**Comment by tsadler1988** [comment]
@solntcev 

It is based on the user agent. The rules vary from one manufacturer to another, but see below for the rules around 2015 LG models:

Model | User agent contains
------------ | -------------
a5lr | 'LG NetCast' AND 'DTV_W15L'
a5lr | 'LG NetCast' AND 'DTV_W15L'
a5lr | 'LG NetCast' AND 'DTV_W15L'

**Comment by tsadler1988** [comment]
a5lr | 'LG NetCast' AND 'DTV_W15L'
