### ISSUE TITLE
deployment doc: samsung maple and others

### ISSUE THREAD

**Issue by pajooh** [fmtvp/tal#281]
Hello all
I'm trying to deploy the example app into samsung emulator, and i got some troubles.
first of all, there is no device config for any samsung device (in my case maple). 
it seems that i'm supposed to use default config. but how to set pagestrategy now?
so i set pagestrategy manually to ```samsungmaple``` in the index.php and generated the html file from that. providing the required ```widget.info``` and ```config.xml```, the app can be loaded into emulator.
but now, the remote key's is not working (i think the focus is not set)
what should i do, is it something that i do wrong? any help would be highly appreciated.

generally speaking, it is good to have device specific deployment guides in the docs.

**Comment by pajooh** [comment]
i've created a device config for maple as a modification of default-webkit:
```json
{
  "pageStrategy": "samsungmaple",
  "modules": {
    "base": "antie/devices/browserdevice",
    "modifiers": [
      "antie/devices/anim/styletopleft",
      "antie/devices/media/samsung_maple",
      "antie/devices/media/samsung_maple_unload",
      "antie/devices/mediaplayer/samsung_maple",
      "antie/devices/net/default",
      "antie/devices/data/nativejson",
      "antie/devices/storage/cookie",
      "antie/devices/logging/onscreen",
      "antie/devices/logging/xhr",
      "antie/devices/logging/jstestdriver",
      "antie/devices/exit/samsung_maple",
      "antie/devices/exit/broadcast/samsung_maple",
    ]
  },
  "logging": {
    "level": "none"
  },
  "streaming": {
    "video": {
      "mediaURIFormat": "%href%",
      "supported": [
        {
          "protocols": [
            "http"
          ],
          "encodings": [
            "h264"
          ],
          "transferFormat": [
            "hls",
            "plain"
          ],
          "maximumBitRate": 3600,
          "maximumVideoLines": 1080
        }
      ]
    },
    "audio": {
      "mediaURIFormat": "%href%",
      "supported": [
        {
          "protocols": [
            "http"
          ],
          "encodings": [
            "aac"
          ],
          "maximumBitRate": 192
        }
      ]
    }
  },
  "input": {
    "map": {
      "29443": "ENTER",
      "88": "BACK",
      "4": "LEFT",
      "29460": "UP",
      "5": "RIGHT",
      "29461": "DOWN",
      "31": "INFO",
      "70": "STOP",
      "71": "PLAY",
      "72": "FAST_FWD",
      "74": "PLAY_PAUSE",
      "69": "REWIND",

    }
  },
  "accessibility": {
    "captions": {
      "supported": [
        "application/ttaf+xml"
      ]
    }
  },
  "layouts": [
    {
      "width": 960,
      "height": 540,
      "module": "%application%/appui/layouts/540p",
      "classes": [
        "browserdevice540p"
      ]
    },
    {
      "width": 1280,
      "height": 720,
      "module": "%application%/appui/layouts/720p",
      "classes": [
        "browserdevice720p"
      ]
    }
  ],
  "networking": {
    "supportsJSONP": true
  }
}
```
the key codes is taken from [samsung official guide](http://www.samsungdforum.com/Guide/?FolderName=art00046&FileName=index.html), but now each key works just once. i.e. if i press Enter to enter "Carousel Example", hitting it again does not work to come back to main menu. other keys have the same situation!

**Comment by subsidel** [comment]
Hi @pajooh, which emulator are you using when you experience this issue? We do not use any internally, instead we use actual TV's for our testing. 
Due to the number of manufacturers we support, and as different devices can have differing instructions for different models/years of device, we would advise that developers use the manufacturer's official documentation.

**Comment by tsadler1988** [comment]
Hi @pajooh,

We will close this for now, but please feel free to reopen in the future if you have any follow up.

Tom
