### ISSUE TITLE
Cookie Storage Location

### ISSUE THREAD

**Issue by joeyjojo** [fmtvp/tal#284]
Currently the domain and the path of the cookie storage location are 'hardcoded' into the application or not settable, we need to be able to:

1. Set the domain
2. Have the path value as 'pathless' or use the current behaviour

**Comment by dhurrell** [comment]
Bear in mind that "storage" in TAL is generic - although cookie storage is the mechanism currently used by most devices, we also offer a simple non-persistent key-value store and (not in this repo) device-specific persistent local storage.

If you want to deal with cookies only, it's possible that you should do it outside of TAL. Alternatively, if you choose to extend the storage API (e.g. with support for optional "hints"), your client app must consider that devices won't necessarily be using cookies to store your data.

**Comment by sdclibbery** [comment]
This is a very good point David. We need to think carefully about what to
do here, since we need to somehow maintain the old behaviour for other (non
iPlayer) apps and open source adopters.
I think the most obvious would be a new modifier for the new behaviour, but
then we would have to specify it in all the iPlayer app configs :-/

**Comment by joeyjojo** [comment]
If we make this an optional extra argument object then other 'storage providers' will basically ignore it whilst the cookie storage provider understands how to use it and what to do.

The namespace argument used currently by Cookie follows this pattern, I think. The init accepts a namespace argument which session.js doesn't.

Does this make sense?

**Comment by sdclibbery** [comment]
That's true. If the modifiers are already following this (optional
argument) pattern, then it sounds fine.

**Comment by jmalk** [comment]
I see a merged pull request - should this issue be closed, or was the work only in response to a subset of the problem?

**Comment by joeyjojo** [comment]
Resolved by #285
