### ISSUE TITLE
Can't run on samsungtv [missing documentation?]

### ISSUE THREAD

**Issue by shawninder** [fmtvp/tal#290]
Putting an app on Samsung TV usually implies providing it with a widgetlist.xml and a zip file. I can't find either of these anywhere in tal. Nor can I find any documentation explaining how to, for example, install the example app on a(ny) TV. I can get the example app running on my computer at 127.0.0.1:1337. It works. But how do I install it on the TV?

**Comment by subsidel** [comment]
As per https://github.com/fmtvp/tal/issues/281#issuecomment-144425698 we do not intend to document installation instructions for specific manufacturors as it can change year on year and by model, we would recommend that you use the offical documentation. http://www.samsungdforum.com/
