### ISSUE TITLE
Updating version in bower.json

### ISSUE THREAD

**Issue by DNR500** [fmtvp/tal#297]
Process needs to include the update and maintainance of the version number in bower.json. Bower is a dependency managment tool for javascript - allows for easy distribution of the codebase to those interested in using it. The version number in the bower.json needs to be show the most up-to-date release tag available for a project.

**Comment by subsidel** [comment]
Hi Nathan, we will look at adding a grunt task that will update version numbers for when we tag our releases.

**Comment by subsidel** [comment]
See: #305
