### ISSUE TITLE
Npm tal actually points to node-tal

### ISSUE THREAD

**Issue by DNR500** [fmtvp/tal#298]
see https://www.npmjs.com/package/tal

"npm install tal" - Would actually import https://github.com/bbcrd/node-tal into a project

This is confusing! npm is great way to allow our open source projects to be distributed - should we be using this to point to the open source TAL project rather than node-tal?

**Comment by AlexChesters** [comment]
:+1:

**Comment by jmalk** [comment]
This has since been fixed, thanks for pointing it out.
