### ISSUE TITLE
TAL Google Group

### ISSUE THREAD

**Issue by AlexChesters** [fmtvp/tal#301]
The [TAL FAQs](http://fmtvp.github.io/tal/faq.html) at the bottom link to the [TAL Google Group](https://groups.google.com/forum/#!forum/talopensource), which looks like no-one from our end is paying attention too. If this is the case do we want to still encourage people to go there with queries?

**Comment by tsadler1988** [comment]
Found the owner of the Google Group and it has now been taken down. #306  raised to remove references in the documentation.

**Comment by jmalk** [comment]
PR merged, so I think that's this issue CLOSED.
