### ISSUE TITLE
We shouldn't run the travis build for the gh-pages branch

### ISSUE THREAD

**Issue by AlexChesters** [fmtvp/tal#303]
According to the [Travis docs](http://docs.travis-ci.com/user/customizing-the-build/#Whitelisting-or-blacklisting-branches) the `gh-pages` branch isn't built unless you explicitly tell it to be, yet ours does.

However the same docs also mention:
```
Note that for historical reasons .travis.yml needs to be present on all active branches of your project.
```

Maybe we need to add a `.travis.yml` file to the `gh-pages` branch?

**Comment by tsadler1988** [comment]
I think this may have been a temporary GitHub glitch, seeing as the `gh-pages` pull request I made (#304) has not attempted to run the Travis build.

**Comment by tsadler1988** [comment]
My branch name was prefixed with `gh-pages' whereas yours (#302) was not. I wonder if this could be the cause?

**Comment by AlexChesters** [comment]
Hmm, that could be the reason! Happy to close this if you are?

**Comment by tsadler1988** [comment]
We'll keep an eye on it and have another look if this happens again.
