### ISSUE TITLE
Validating whitespace

### ISSUE THREAD

**Issue by tsadler1988** [fmtvp/tal#307]
We are not able to validate whitespace via JSHint. Some potential tools for doing this include:
* [JSCS](http://jscs.info/)
* [grunt-lintspaces](https://github.com/schorfES/grunt-lintspaces)
* [ESLint](http://eslint.org/)
* [Code Climate](https://codeclimate.com/)
* [Hound](https://houndci.com/)

**Comment by tsadler1988** [comment]
ESLint or JSCS might be best, as they could also replace JSHint. If we were to use another, it would mean we would have 2 linters.

**Comment by subsidel** [comment]
[eslint branch](https://github.com/fmtvp/tal/tree/eslint): just run `grunt lint` to see it go

**Comment by subsidel** [comment]
Migration linting to eslint has been decided to be the way forward with this issue, for the time being running both and then removing jshint (see #325)
