### ISSUE TITLE
queuedComponentInit is not defined

### ISSUE THREAD

**Issue by designreact** [fmtvp/tal#323]
The testing documentation http://fmtvp.github.io/tal/testing.html states that the following helper methods are supported queuedRequire, queuedApplicationInit and queuedComponentInit.

Having upgraded to use Jasmine test runner, tests we had running using the TAL test runner that use queuedComponentInit now fail with: 'ReferenceError: queuedComponentInit is not defined'.

Either the documentation needs updating or queuedComponentInit needs to be added to jstestdriver-adapter.js

**Comment by designreact** [comment]
I have updated our tests to use queuedApplicationInit. However a decision on updating the documentation will still need to be made.

**Comment by tsadler1988** [comment]
Thanks for raising this @designreact, this has not been used as far as we know so we will remove it from our documentation.

**Comment by subsidel** [comment]
Fixed in e57473a260a020125ed077a046f52b23e2e4b695
