### ISSUE TITLE
Samsung tizen test converage is lacking

### ISSUE THREAD

**Issue by yameen** [fmtvp/tal#331]
We need to address the following deficits in the testing of the samsung tizen broadcast source tests.
(tal/static/script-tests/tests/devices/broadcastsource/tizentvsourcetest.js)

- No test for setPosition method (full screen of the app and related tests)
- No test for stopCurrentChannel
- No check getChannelNameList returns correct list of channels
- No test of API destroy method
- No setChannelByName tests

Addressing this deficit is something that should be done as per our policy of accepting code into the TAL codebase.
This arose from #327

**Comment by yameen** [comment]
@mkarwacki This is the issue that relates to test coverage we discussed on the phone. Please use this along with comparing with tests in:
tal/static/script-tests/tests/devices/broadcastsource/samsungtvsourcetest.js
tal/static/script-tests/tests/devices/broadcastsource/hbbtvsourcetest.js

Please do not hesitate to contact me for clarification or more details.

Thanks

**Comment by kzurawski** [comment]
Hi @yameen 
I've added required tests to tizentvsourcetest.js file, according to test cases from older Samsung TV platforms (samsungtvsourcetest.js). I hope that it is enough, also I checked the file with eslint.

Please review and accept my pull request #335

**Comment by yameen** [comment]
Hello @kzurawski 
Thanks for doing that, you will notice that my colleague @subsidel has approved the merge into our master.
Happy to close this issue now. Looks like we are good to go from this aspect.
