### ISSUE TITLE
Consider using templates for issues and pull requests

### ISSUE THREAD

**Issue by AlexChesters** [fmtvp/tal#340]
Since Github now supports [templates for issues and pull requests](https://github.com/blog/2111-issue-and-pull-request-templates), we should consider using these for TAL. I think they'd go some way to ensuring that issues and pull requests contain the correct information

**Comment by tsadler1988** [comment]
Thanks for flagging this new functionality @AlexChesters, but the current volume and size of issues and pull request we are receiving doesn't warrant templating at this point.

This is definitely something to consider if we start getting unmanageable issues/pull requests in the future.
