### ISSUE TITLE
Two variations of array.indexof shim

### ISSUE THREAD

**Issue by AlexChesters** [fmtvp/tal#342]
We currently have two variations of the `array.indexof` shim for pre ES5 browsers. We have the [full shim](https://github.com/fmtvp/tal/blob/master/static/script/lib/array.indexof.js) as taken from Mozilla, whilst another implementation is present in [intervalformat.js](https://github.com/fmtvp/tal/blob/master/static/script/lib/intervalformat.js#L20-L27). Ideally we should have only one variation of the `array.indexof` shim.

**Comment by lukejpreston** [comment]
I would like to see us bringing in the ES5/6/7/8/9/... shim shams and not on a as and when basis. But it was deemed testing this would be too costly. That said, who is responsible for bringing in the shim/sham? TAL or your server side solution?

**Comment by AlexChesters** [comment]
I'd like to see us do a full ES5 shim as well, @joeyjojo has raised this point in [#273](https://github.com/fmtvp/tal/issues/273#issue-98735438).

The second question is a bigger one, and one I don't have an answer too!

**Comment by subsidel** [comment]
This ultimately seems to be a duplicate of #273, which is about correcting the implementation of shims around Array.indexof etc. Closing as duplicate for now, unless we really think it is different
