### ISSUE TITLE
Consider something like Greenkeeper

### ISSUE THREAD

**Issue by AlexChesters** [fmtvp/tal#346]
We have quite a few dependencies in our [package.json](https://github.com/fmtvp/tal/blob/master/package.json) and as far as I'm aware (I'm happy to be wronged) we don't have any defined process for managing these dependencies.

We could use something like [greenkeeper](http://greenkeeper.io/) for this. I like the sound of it for 2 main reasons.
1. It needs very little (1 terminal command) setup on our side
2. As `tal` is open-source, it's free!

I'd be interested to get people's thoughts and opinions on this.

**Comment by joeyjojo** [comment]
I think its a worthy experiment to see if it adds value.

**Comment by roberton** [comment]
It looks interesting. I'll offer a contrary viewpoint though!
All our dependencies are for development, not modules the we use at runtime. As such it doesn't seem _so_ important that we update rigorously, unlike if we were worried about picking up security fixes or other run-time bugs. Therefore the gain seems less that it would for some projects, against adding a little bit of complexity to our build system.

Any validity to this line of thought? Btw, this line or arguing doesn't apply to Fuji etc; maybe that would be a good place to try it, if it were free :-(

**Comment by joeyjojo** [comment]
I raised this against one of our private repos as something to try a while ago, given the free plan allows 1 private repo this is probably a better idea.

**Comment by AlexChesters** [comment]
Closing as their doesn't seem to be a great desire for this (for `tal` anyway!)
