### ISSUE TITLE
Documentation about animating element style properties

### ISSUE THREAD

**Issue by bastuijnman** [fmtvp/tal#356]
Hello,

I've got a question about animating style properties in TAL, I was using `tweenElementStyle` for this, but it's listed as `protected` in your documentation. 

I'm not seeing any alternative for this method in the code, is there any reason why it's listed as `protected`? Also, if it's ok to be used as a public method I can also add some documentation about the method if needed.

Kind regards,

Bas Tuijnman
24i

**Comment by dhurrell** [comment]
Hi Bas,

I don't know why this method is listed as "protected". Given that methods described in our [animation documentation](http://fmtvp.github.io/tal/widgets/animation.html) such as `moveElementTo` are also marked as protected, I can only imagine it's a mistake. We certainly use `tweenElementStyle` ourselves.

Feel free to add some documentation! I see there is [already some JsDoc for this method](http://fmtvp.github.io/tal/jsdoc/symbols/antie.devices.Device.html#tweenElementStyle) (albeit misleadingly labelled "protected") so I guess it just needs a mention on the animation page above.

Thanks,
David

**Comment by AlexChesters** [comment]
Fixed in #357
