### ISSUE TITLE
Roku support

### ISSUE THREAD

**Issue by vgrafe** [fmtvp/tal#362]
Hi there, 

I can see on the config/devices files that many roku devices seem supported, but there is no explanation about how to compile/package the code in something accepted, as Roku does not allow webviews.

Looks like BBC's Roku iPlayer is built on top of TAL but I can't find any information about how to achieve this. Is there something I missed?

**Comment by vgrafe** [comment]
Oh well, just found my answer in #57. Closing my issue and contacting Roku. Wish me luck!

**Comment by rahulkrish** [comment]
We are exploring at the possibility of using TAL for Roku development. Any luck post reaching out to Roku team or should we stick to Brightscript ?

**Comment by vgrafe** [comment]
No luck. It looks like Roku won't change their mind about Brightscript being a requirement for apps.
