### ISSUE TITLE
Node 0.10 EOL is soon

### ISSUE THREAD

**Issue by subsidel** [fmtvp/tal#385]
According to https://github.com/nodejs/LTS#lts_schedule node 0.10 LTS support will end "2016-10-01" and the .travis file uses this version. 

We should move to the latest LTS version.

**Comment by subsidel** [comment]
#396 removes the only thing that needed old node version.
I have now tested running tests etc on v6.6.0 and v4.4.7 on that branch, so if that is merged we should be able to pick a newer/more supported version of node and use it.

**Comment by AlexChesters** [comment]
Given that Node in `TAL` is only used for local development (i.e. tests and tooling) I feel that we should move to 6.x.x whilst we are upgrading anyway. Node 6 is due to become LTS within a week or so anyway so it makes sense.

**Comment by subsidel** [comment]
I'll open a PR
