### ISSUE TITLE
Evaluating TAL for use in Smart TV project

### ISSUE THREAD

**Issue by caridley** [fmtvp/tal#388]
We are looking for the right framework to use for a new version of our video application for smart TVs. Samsung is our primary target platform, but portability to other HTML/JavaScript TV platforms will be important. We are considering using the BBC’s TAL framework and have a few questions.

Is the BBC still using this framework for their TV applications?

How many other application are using TAL?

We have an Angular I based desktop browser application that provides the same functionality as our SmartTV app, would it be feasible to reuse some of that applications Angular components in a TAL based Smart TV app? Could Angular service components be used in a TAL application?

Are the viable alternatives to TAL?

Are there plans for further evolution of TAL?

Thanks
Aidan

**Comment by subsidel** [comment]
Hi Aidan, thanks for your interest in TAL.

In answer to your questions:

1) yes - We are using the TAL framework for all of our TV applications
2) BBC iPlayer, News, Sport and Red Button+ TV apps use TAL
3) Potentially as this is just javascript. However we have not explored Angular integration ourselves
4) Many vendors (open and closed) provide libraries for smart tv development, however we believe that TAL has great strength with it's breadth of compatible devices
5) Yes - all of our TV Apps are based on TAL and it is under active development.

**Comment by AlexChesters** [comment]
@caridley we're going to close this now as we think we've answered all of your questions, thanks for your interest and please get in touch if you have any further questions! 😄
