### ISSUE TITLE
Getter access to the MediaElement 'buffered' TimeRanges object

### ISSUE THREAD

**Issue by TrevorLawford** [fmtvp/tal#421]
**Request from the BT HTML5 BtPlayer App development team.**

Implementing the LineSpeedChecker has required me to access the **buffered** TimeRanges object of the TAL’s private Media Element _directly_. (This is an HTML5 component, not a TAL-specific object.)

- https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/buffered
- https://developer.mozilla.org/en-US/docs/Web/API/TimeRanges

I read the length attribute and the end() getter function call.

Currently I am forced to access this illegally via...
`RuntimeContext.getDevice().getMediaPlayer()._mediaElement.buffered`

We request that an _official_ getter be provided to return the 'buffered' object.

**Comment by tsadler1988** [comment]
Hi Trevor,

There is an existing `getPlayerElement()` function on the TAL Media Player - https://github.com/fmtvp/tal/blob/master/static/script/devices/mediaplayer/html5.js#L370 - so you could do `RuntimeContext.getDevice().getMediaPlayer().getPlayerElement().buffered`. Would this work for you? 

I'd rather not pollute the TAL Media API with HTML5 specifics. `getPlayerElement()` is not HTML5 specific, as it provides access to the underlying implementation for CEHTML and Samsung Maple as well. I'd rather `getPlayerElement()` hadn't been added either, as TAL should abstract away all device specifics, but unfortunately there is sometimes a need to access the underlying implementation.

Tom

**Comment by TrevorLawford** [comment]
Tom,
I missed this completely. Of course it's exactly what I need.
Apologies, and thanks.
Trevor.
